/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import simulacroexame2.memorygame.ArrayCardGenerator;

/**
 *
 * @author fernando.pedridomarino
 */
public class MemoryGame extends javax.swing.JFrame {

    /**
     * Creates new form MemoryGame
     */
    public MemoryGame() {
        initComponents();
    }
       
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCartas = new javax.swing.JPanel();
        cartaButton1 = new javax.swing.JToggleButton();
        cartaButton2 = new javax.swing.JToggleButton();
        cartaButton3 = new javax.swing.JToggleButton();
        cartaButton4 = new javax.swing.JToggleButton();
        cartaButton5 = new javax.swing.JToggleButton();
        cartaButton6 = new javax.swing.JToggleButton();
        cartaButton7 = new javax.swing.JToggleButton();
        cartaButton8 = new javax.swing.JToggleButton();
        cartaButton9 = new javax.swing.JToggleButton();
        cartaButton10 = new javax.swing.JToggleButton();
        cartaButton11 = new javax.swing.JToggleButton();
        cartaButton12 = new javax.swing.JToggleButton();
        panelTitulo = new javax.swing.JPanel();
        dificultadeLabel = new javax.swing.JLabel();
        puntuacionLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nivelLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCartas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCartas.setPreferredSize(new java.awt.Dimension(650, 850));
        panelCartas.setLayout(new java.awt.GridLayout(3, 4));

        cartaButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton1.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton1.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton1.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton1);

        cartaButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton2.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton2.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton2.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton2);

        cartaButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton3.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton3.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton3.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton3);

        cartaButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton4.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton4.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton4.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton4);

        cartaButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton5.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton5.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton5.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton5);

        cartaButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton6.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton6.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton6.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton6);

        cartaButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton7.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton7.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton7.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton7);

        cartaButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton8.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton8.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton8.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton8);

        cartaButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton9.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton9.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton9.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton9);

        cartaButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton10.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton10.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton10.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton10);

        cartaButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton11.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton11.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton11.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton11);

        cartaButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaButton12.setMaximumSize(new java.awt.Dimension(200, 200));
        cartaButton12.setMinimumSize(new java.awt.Dimension(200, 200));
        cartaButton12.setPreferredSize(new java.awt.Dimension(200, 200));
        panelCartas.add(cartaButton12);

        getContentPane().add(panelCartas, java.awt.BorderLayout.CENTER);

        panelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 1);
        flowLayout1.setAlignOnBaseline(true);
        panelTitulo.setLayout(flowLayout1);

        dificultadeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dificultadeLabel.setText("Dificultade:");
        panelTitulo.add(dificultadeLabel);

        puntuacionLabel.setText("Puntuación:");
        panelTitulo.add(puntuacionLabel);

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        nivelLabel.setText("Nivel:");
        jPanel4.add(nivelLabel);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Normal", "Dificil" }));
        jPanel4.add(jComboBox1);

        jButton1.setText("Nova Partida");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton2.setText("Saír");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.getAccessibleContext().setAccessibleName("SairButton");

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       private void startGame();
       private void gameStatus();
       private void unselectedButtons();
       private void checkGameOver();
       private void uncover();
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cartaButton1;
    private javax.swing.JToggleButton cartaButton10;
    private javax.swing.JToggleButton cartaButton11;
    private javax.swing.JToggleButton cartaButton12;
    private javax.swing.JToggleButton cartaButton2;
    private javax.swing.JToggleButton cartaButton3;
    private javax.swing.JToggleButton cartaButton4;
    private javax.swing.JToggleButton cartaButton5;
    private javax.swing.JToggleButton cartaButton6;
    private javax.swing.JToggleButton cartaButton7;
    private javax.swing.JToggleButton cartaButton8;
    private javax.swing.JToggleButton cartaButton9;
    private javax.swing.JLabel dificultadeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nivelLabel;
    private javax.swing.JPanel panelCartas;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel puntuacionLabel;
    // End of variables declaration//GEN-END:variables
}
